services:
  openlist:
    build:
      context: .
      dockerfile: Dockerfile.allinone
      additional_contexts:
        frontend: ../openlist-frontend
      args:
        VERSION: custom
        GIT_COMMIT: ${GIT_COMMIT:-local}
    image: 'openlist-custom:latest'
    container_name: openlist
    restart: always
    volumes:
      - 'openlist-data:/opt/openlist/data'
    ports:
      - '5244:5244'
    environment:
      - UMASK=022
      - TZ=Asia/Shanghai

volumes:
  openlist-data:
